server:
  port: 8083
spring:

  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.137.2:9300
  rabbitmq:
    host: 192.168.137.2
    username: leyou
    password: leyou
    virtual-host: /leyou
  datasource:
    url: jdbc:mysql://192.168.137.2:3306/leyou?serverTimezone=UTC
    username: leyou
    password: leyou
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放 （retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数 （show variables like '%timeout%')
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式： ((core_count * 2) + effective_spindle_count)


  jackson:
    default-property-inclusion: non_null  # 忽略json数据的null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10