server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://192.168.31.185:3306/leyou?serverTimezone=UTC
    username: root
    password: Caiahao0.
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放 （retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数 （show variables like '%timeout%')
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式： ((core_count * 2) + effective_spindle_count)
  rabbitmq:
    host: 192.168.137.2
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: leyou-item-exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10