server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传大小

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
#fastdfs分布式文件管理服务器
fdfs:
  so-timeout: 3000 # 超时时间
  connect-timeout: 601 # 连续超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # 跟踪服务器
    - 192.168.137.2:22122