server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.137.2
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAI4GDGXkKRgaAa5kfPTZWW # 你自己的accessKeyId
    accessKeySecret: 10ZGw0J4mRpXg3muS2AViW4SUXVjb1 # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_205398338 # 模板名称